inherit_gem:
  rubocop-config-umbrellio: lib/rubocop.yml

AllCops:
  TargetRubyVersion: 2.3
  Include:
    - bin/*
    - lib/**/*.rb
    - spec/**/*.rb
    - Gemfile
    - Rakefile
    - umbrtonic.gemspec
